services:
  mysql-db:
    image: mysql:8.0
    container_name: ecommerce-mysql-db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: